package generate

import (
	"math/rand"

	"github.com/Percona-Lab/random-data-load/db"
	"github.com/rs/zerolog/log"
)

// SkewedSample reproduces how often a foreign key repeats the same parent.
//
// A statistics export holds most_common_freqs for the key columns of the source
// database, and those frequencies are what a planner reads to size a hash
// join's build side: most_common_freqs[1] of the inner join column decides
// which side gets built, which in the ten-table case of the study was the
// single hardest thing to reproduce. The values beside those frequencies are
// the source's own parent ids and are of no use here, but the frequencies are
// reproducible without them -- point that share of the child's rows at one
// parent row each and the column ends up as skewed as it was measured.
//
// Everything else is left to the sampler underneath, which fills the rows this
// does not claim. So a relationship keeps whatever distribution it was given
// and gains the measured spikes on top of it.
type SkewedSample struct {
	sampleCommon
	base  Sampler
	freqs []float64
}

func (s *SkewedSample) Sample() error {
	if err := s.base.Sample(); err != nil {
		return err
	}

	// Which rows get one of the hot parent rows, and which hot row each of
	// them gets. The parent rows are picked by position and any set of
	// distinct ones does: the local ids were generated by this run, so no row
	// of the parent is more "the common one" than another.
	claimed := map[int64][]int{}
	for row := range s.values {
		hot, drawn := s.draw()
		if !drawn {
			continue
		}
		claimed[hot] = append(claimed[hot], row)
	}
	if len(claimed) == 0 {
		return nil
	}

	offsets := make([]int64, 0, len(s.values))
	rows := make([]int, 0, len(s.values))
	for hot, claimedRows := range claimed {
		for _, row := range claimedRows {
			offsets = append(offsets, hot)
			rows = append(rows, row)
		}
	}
	return s.fillFromRowNumbers(rows, offsets)
}

// draw picks which of the hot parent rows this child row points at, if any.
//
// Each frequency is a share of the whole column, so they are tested against
// what is left rather than against 1: without dividing, a value at 0.34 sitting
// behind one at 0.37 would only reach 34% of the 63% the first one left.
// InjectIndexValue draws the generated values the same way.
func (s *SkewedSample) draw() (int64, bool) {
	remaining := 1.0
	for i, freq := range s.freqs {
		if freq <= 0 || remaining <= 0 {
			continue
		}
		if rand.Float64() < freq/remaining {
			return int64(i), true
		}
		remaining -= freq
	}
	return 0, false
}

// newSkewedSample wraps a sampler with the key skew an export measured, and
// returns the sampler untouched when there is nothing to reproduce.
//
// More hot values than the parent has rows cannot be reproduced -- each one
// needs a row of its own -- so the list is cut down to what the parent can
// carry, keeping the most common ones, which are the ones a plan turns on.
func newSkewedSample(base Sampler, constraint *db.Constraint, values [][]Getter, tableSize int64, freqs []float64, fkCli *ForeignKeyLinks) Sampler {
	if len(freqs) == 0 || tableSize <= 0 {
		return base
	}
	if int64(len(freqs)) > tableSize {
		logOnce("keySkewTruncated:"+constraint.ConstraintName, func() {
			log.Warn().Str("parent", constraint.ReferencedTableName).Int64("parentRows", tableSize).Int("values", len(freqs)).
				Msgf("the export measured %d common values on this key and %s only holds %d rows, so only the %d most common of them can be given a row of their own",
					len(freqs), constraint.ReferencedTableName, tableSize, tableSize)
		})
		freqs = freqs[:tableSize]
	}

	s := &SkewedSample{base: base, freqs: injectionRates(freqs, tableSize)}
	s.Init(constraint.ReferencedFields, constraint.ReferencedTableSchema, constraint.ReferencedTableName,
		constraint.ConstraintName, values, tableSize, fkCli)
	if len(s.freqs) == 0 {
		return base
	}

	logOnce("keySkew:"+s.relationshipKey(), func() {
		log.Info().Str("parent", constraint.ReferencedTableName).Strs("columns", constraint.ColumnsName).Int("values", len(freqs)).Float64("mostCommon", freqs[0]).
			Msgf("reproducing the key skew the export measured on %s: %.4f of the rows point at one row of %s, and the rest keep the sampling they were given",
				constraint.ColumnsName[0], freqs[0], constraint.ReferencedTableName)
	})
	return s
}

// injectionRates turns the shares that were measured into the shares that have
// to be claimed to produce them.
//
// The rows this does not claim are still filled by the sampler underneath, and
// that sampler lands on the hot parent row now and then by itself. Claiming
// the measured share outright therefore overshoots it by whatever the base
// contributes, which over a small parent is not a rounding error: a 200-row
// dimension table sampled evenly adds half a percent to every value, a 10-row
// one adds seven.
//
// So each share is reduced by what a sampler spreading evenly over the parent
// would contribute. A sampler deliberately concentrated somewhere -- zipf,
// normal -- contributes more than that to the rows it favours and less to the
// others, so the correction is only approximate there. That is the same
// approximation as asking for a measured skew and a chosen distribution at
// once, which is what the caller did.
//
// A share the base already produces on its own is dropped: there is nothing to
// add to it.
func injectionRates(measured []float64, tableSize int64) []float64 {
	even := 1 / float64(tableSize)

	rates := make([]float64, 0, len(measured))
	for _, share := range measured {
		rate := (share - even) / (1 - even)
		if rate <= 0 {
			log.Debug().Float64("share", share).Int64("parentRows", tableSize).
				Msg("a measured key share is no larger than what the sampling produces on its own, leaving it alone")
			break
		}
		rates = append(rates, rate)
	}
	return rates
}

// keyFrequenciesFor returns the skew an export measured on this foreign key.
//
// Only a single-column key has one. The common values of one column of a
// composite key say how often that column repeats, not how often the pair
// does, and sampling on one of them would claim a skew the export never
// measured.
func (in *Insert) keyFrequenciesFor(constraint *db.Constraint) []float64 {
	if len(constraint.ColumnsName) != 1 {
		return nil
	}
	freq, ok := in.frequencies[constraint.ColumnsName[0]]
	if !ok {
		return nil
	}
	return freq.KeyFrequencies
}
